In [ ]:
import numpy as np

Creating and modifying an array

In [ ]:
a = np.arange(0,10)

In [ ]:
print(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1] = 76

In [ ]:
print(a)

[ 0 76  2  3  4  5  6  7  8  9]


finding min max and mean

In [ ]:
print(min(a))
print(max(a))
print(np.mean(a))

0
76
12.0


reshaping and flattening an array

In [ ]:
print(a.reshape(2,5))

[[ 0 76  2  3  4]
 [ 5  6  7  8  9]]


In [ ]:
print(a.flatten())

[ 0 76  2  3  4  5  6  7  8  9]


create two 2x 2 arrays and stack them verticallly and horizontally

In [ ]:
a = np.arange(1,5).reshape(2,2)

In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
b = np.arange(5,9).reshape(2,2)

In [ ]:
print(b)

[[5 6]
 [7 8]]


In [ ]:
c = np.vstack((a,b))

In [ ]:
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
d = np.hstack((a,b))

In [ ]:
print(d)

[[1 2 5 6]
 [3 4 7 8]]


convert a 1d array of size 9 into a 3x3 matrix

In [ ]:
a = np.arange(9).reshape(3,3)

In [ ]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


create an array from 1 to 10 and reverse it

In [ ]:
a = np.arange(1,11)

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b = a[::-1]

In [ ]:
print(b)

[10  9  8  7  6  5  4  3  2  1]
